### ISSUE TITLE
Template Creator

### ISSUE THREAD

**Issue by FranciscoImanolSuarez** [gdg-x/aura#97]
Can the template builder section be removed?

**Comment by barisdongel** [comment]
I think it's not a big problem. Those who make the theme should be given their right :D

**Comment by FranciscoImanolSuarez** [comment]
Not obviously, I was thinking of giving it the credits or rights in the footer as I'm customizing the theme.

**Comment by bharatagsrwal** [comment]
Hey @FranciscoImanolSuare, you can remove but you have to give credits to the creator which is **[GDG Jalandhar](https://gdgjalandgar.com)** of the template and on what project is based upon as we mentioned in the footer, **[Project Based on Aura](https://github.com/gdg-x/aura)**, so you can customize the theme as you like since it is an open-source project.

Regards
Bharat Agarwal
